### ISSUE TITLE
Самоубийство при выстреле вниз

### ISSUE THREAD

**Issue by Str1ker17** [CursesGames/CursesStrike#3]
Возникает на этом коммите: fbf63634b7de3fcb7ba4def72cff75ee01df36eb
Как можно попытаться воспроизвести:
Запустить сервер, подключить к нему одного клиента. Нажать пробел, перейдя в игровой режим. Немного подвигаться по карте без поворота, двумя нажатиями E подряд развернуться вниз. Выстрелить единожды, дождаться когда пуля дойдёт до конца. Сместиться на 1 позицию влево, выстрелить единожды. Если зелёныймаркер исчез с карты - значит, игрок убил себя.

Лог сервера:
```
[D] Map sent to client 127.0.0.1:32991
[!] received CONNECT2 from client
[!] received MOVE from client
[!] received FIRE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received MOVE from client
[!] received FIRE from client
[!] received FIRE from client
[!] received FIRE from client
[!] received ROTATE from client
[!] received ROTATE from client
[!] received FIRE from client
[!] received MOVE from client
[!] received FIRE from client
```
Дамп сервера (новая фича, команда `dump` в консоли сервера) после самоубийства в прикреплённом файле.
[dump_server.log](https://github.com/CursesGames/CursesStrike/files/2267576/dump_server.log)

**Comment by tornem** [comment]
85b9b15af3caeb94e45f8644da8084b3e5a3c4c5 completed!

**Comment by tornem** [comment]
85b9b15af3caeb94e45f8644da8084b3e5a3c4c5 completed!
